@Regression

Feature: C285 - Entry Number - importer-person

  @test @a11y @ZAP
  Scenario: User is a CDS Trader - happy path (entry number) - duplicate Entry Number
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB123456789012345" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I navigate to the "Start Page"
    And I click "Start now" on "Start Page"
    Then I am presented with the "Enter Movement Reference Number Page"
    When I enter "666541198B49856762" on "Enter Movement Reference Number Page"
    And I click continue on "Enter Movement Reference Number Page"
    Then I am presented with the "Enter Declaration Details Page"
    When I enter "" on "Enter Declaration Details Page"
    And I click continue on "Enter Declaration Details Page"
    Then I am presented with the "Who Is The Declarant Page"
    When I select radio button "0" on "Who Is The Declarant Page"
    And I click continue on "Who Is The Declarant Page"
    Then I am presented with the "Enter Claimant Details As Individual Page"
    When I enter "" on "Enter Claimant Details As Individual Page"
    And I select radio button "true" on "Enter Claimant Details As Individual Page"
    And I click continue on "Enter Claimant Details As Individual Page"
    Then I am presented with the "Enter Claimant Details As Company Page"
    When I enter "" on "Enter Claimant Details As Company Page"
    And I click continue on "Enter Claimant Details As Company Page"
    Then I am presented with the "Enter Reason For Claim And Basis Page"
    When I select dropdown value "Duplicate MRN or Entry,Mail order goods" on "Enter Reason For Claim And Basis Page"
    And I click continue on "Enter Reason For Claim And Basis Page"
    #Then I am presented with the "Enter Duplicate Movement Reference Number Page"
    When I enter "666541198B49856762" on "Enter Movement Reference Number Page"
    And I click continue on "Enter Movement Reference Number Page"
    Then I am presented with the "Enter Duplicate Declaration Details Page"
    When I enter "" on "Enter Duplicate Declaration Details Page"
    And I click continue on "Enter Duplicate Declaration Details Page"
    Then I am presented with the "Enter Commodity Details Page"
    When I enter "under 500 characters" on "Enter Commodity Details Page"
    And I click continue on "Enter Commodity Details Page"
    Then I am presented with the "Select Duties Page"
    When I select "0,1,2,3,4,5,6,7,8,9,10,11,12,13" on "Select Duties Page"
    And I click continue on "Select Duties Page"
    Then I am presented with the "Enter Claim Page" "A00 - Customs Duty"
    When I enter "2,1" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A20 - Additional Duty"
    When I enter "3,2" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A30 - Definitive Anti-Dumping Duty"
    When I enter "4,3" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A35 - Provisional Anti-Dumping Duty"
    When I enter "5,4" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A40 - Definitive Countervailing Duty"
    When I enter "6,5" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A45 - Provisional Countervailing Duty"
    When I enter "7,6" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "B00 - Value Added Tax"
    When I enter "8,7" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A50 - Customs Duty"
    When I enter "9,8" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A70 - Additional Duty"
    When I enter "10,9" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "11,10" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "12,11" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A90 - Definitive Countervailing Duty"
    When I enter "13,12" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A95 - Provisional Countervailing Duty"
    When I enter "14,13" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "B05 - Value Added Tax"
    When I enter "15,14" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Check Claim Page"
    When I click continue on "Check Claim Page"
    Then I am presented with the "Enter Bank Account Details Page"
    When I enter "" on "Enter Bank Account Details Page"
    And I select checkbox on "Enter Bank Account Details Page"
    And I click continue on "Enter Bank Account Details Page"
    Then I am presented with the "Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Supporting Evidence Scan Progress Page"
    When I select dropdown value "Commercial Invoice" on "Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Supporting Evidence Check Your Answers Page"
    When I click continue on "Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Check Answers Accept Send Page"
    And I click continue on "Check Answers Accept Send Page"

  @test
  Scenario: User is a CDS Trader - happy path (entry number)
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB123456789012345" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I navigate to the "Start Page"
    And I click "Start now" on "Start Page"
    Then I am presented with the "Enter Movement Reference Number Page"
    When I enter "666541198B49856762" on "Enter Movement Reference Number Page"
    And I click continue on "Enter Movement Reference Number Page"
    Then I am presented with the "Enter Declaration Details Page"
    When I enter "" on "Enter Declaration Details Page"
    And I click continue on "Enter Declaration Details Page"
    Then I am presented with the "Who Is The Declarant Page"
    When I select radio button "0" on "Who Is The Declarant Page"
    And I click continue on "Who Is The Declarant Page"
    Then I am presented with the "Enter Claimant Details As Individual Page"
    When I enter "" on "Enter Claimant Details As Individual Page"
    And I select radio button "true" on "Enter Claimant Details As Individual Page"
    And I click continue on "Enter Claimant Details As Individual Page"
    Then I am presented with the "Enter Claimant Details As Company Page"
    When I enter "" on "Enter Claimant Details As Company Page"
    And I click continue on "Enter Claimant Details As Company Page"
    Then I am presented with the "Enter Reason For Claim And Basis Page"
    When I select dropdown value "Duty suspension,Mail order goods" on "Enter Reason For Claim And Basis Page"
    And I click continue on "Enter Reason For Claim And Basis Page"
    Then I am presented with the "Enter Commodity Details Page"
    When I enter "under 500 characters" on "Enter Commodity Details Page"
    And I click continue on "Enter Commodity Details Page"
    Then I am presented with the "Select Duties Page"
    When I select "0,1,2,3,4,5,6,7,8,9,10,11,12,13" on "Select Duties Page"
    And I click continue on "Select Duties Page"
    Then I am presented with the "Enter Claim Page" "A00 - Customs Duty"
    When I enter "2,1" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A20 - Additional Duty"
    When I enter "3,2" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A30 - Definitive Anti-Dumping Duty"
    When I enter "4,3" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A35 - Provisional Anti-Dumping Duty"
    When I enter "5,4" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A40 - Definitive Countervailing Duty"
    When I enter "6,5" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A45 - Provisional Countervailing Duty"
    When I enter "7,6" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "B00 - Value Added Tax"
    When I enter "8,7" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A50 - Customs Duty"
    When I enter "9,8" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A70 - Additional Duty"
    When I enter "10,9" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "11,10" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "12,11" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A90 - Definitive Countervailing Duty"
    When I enter "13,12" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A95 - Provisional Countervailing Duty"
    When I enter "14,13" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "B05 - Value Added Tax"
    When I enter "15,14" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Check Claim Page"
    When I click continue on "Check Claim Page"
    Then I am presented with the "Enter Bank Account Details Page"
    When I enter "" on "Enter Bank Account Details Page"
    And I select checkbox on "Enter Bank Account Details Page"
    And I click continue on "Enter Bank Account Details Page"
    Then I am presented with the "Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Supporting Evidence Scan Progress Page"
    When I select dropdown value "Commercial Invoice" on "Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Supporting Evidence Check Your Answers Page"
    When I click continue on "Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Check Answers Accept Send Page"
    And I click continue on "Check Answers Accept Send Page"

  @test
  Scenario: User is a CDS Trader - happy path (entry number) - no company details
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB123456789012345" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I navigate to the "Start Page"
    And I click "Start now" on "Start Page"
    Then I am presented with the "Enter Movement Reference Number Page"
    When I enter "666541198B49856762" on "Enter Movement Reference Number Page"
    And I click continue on "Enter Movement Reference Number Page"
    Then I am presented with the "Enter Declaration Details Page"
    When I enter "" on "Enter Declaration Details Page"
    And I click continue on "Enter Declaration Details Page"
    Then I am presented with the "Who Is The Declarant Page"
    When I select radio button "0" on "Who Is The Declarant Page"
    And I click continue on "Who Is The Declarant Page"
    Then I am presented with the "Enter Claimant Details As Individual Page"
    When I enter "" on "Enter Claimant Details As Individual Page"
    And I select radio button "false" on "Enter Claimant Details As Individual Page"
    And I click continue on "Enter Claimant Details As Individual Page"
    Then I am presented with the "Enter Reason For Claim And Basis Page"
    When I select dropdown value "Duty suspension,Mail order goods" on "Enter Reason For Claim And Basis Page"
    And I click continue on "Enter Reason For Claim And Basis Page"
    Then I am presented with the "Enter Commodity Details Page"
    When I enter "under 500 characters" on "Enter Commodity Details Page"
    And I click continue on "Enter Commodity Details Page"
    Then I am presented with the "Select Duties Page"
    When I select "0,1,2,3,4,5,6,7,8,9,10,11,12,13" on "Select Duties Page"
    And I click continue on "Select Duties Page"
    Then I am presented with the "Enter Claim Page" "A00 - Customs Duty"
    When I enter "2,1" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A20 - Additional Duty"
    When I enter "3,2" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A30 - Definitive Anti-Dumping Duty"
    When I enter "4,3" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A35 - Provisional Anti-Dumping Duty"
    When I enter "5,4" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A40 - Definitive Countervailing Duty"
    When I enter "6,5" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A45 - Provisional Countervailing Duty"
    When I enter "7,6" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "B00 - Value Added Tax"
    When I enter "8,7" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A50 - Customs Duty"
    When I enter "9,8" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A70 - Additional Duty"
    When I enter "10,9" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "11,10" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "12,11" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A90 - Definitive Countervailing Duty"
    When I enter "13,12" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A95 - Provisional Countervailing Duty"
    When I enter "14,13" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "B05 - Value Added Tax"
    When I enter "15,14" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Check Claim Page"
    When I click continue on "Check Claim Page"
    Then I am presented with the "Enter Bank Account Details Page"
    When I enter "" on "Enter Bank Account Details Page"
    And I select checkbox on "Enter Bank Account Details Page"
    And I click continue on "Enter Bank Account Details Page"
    Then I am presented with the "Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Supporting Evidence Scan Progress Page"
    When I select dropdown value "Commercial Invoice" on "Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Supporting Evidence Check Your Answers Page"
    When I click continue on "Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Check Answers Accept Send Page"
    And I click continue on "Check Answers Accept Send Page"

  @test @a11y @ZAP
  Scenario: User is a CDS Trader - happy path (entry number) - duplicate MRN
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB123456789012345" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I navigate to the "Start Page"
    And I click "Start now" on "Start Page"
    Then I am presented with the "Enter Movement Reference Number Page"
    When I enter "666541198B49856762" on "Enter Movement Reference Number Page"
    And I click continue on "Enter Movement Reference Number Page"
    Then I am presented with the "Enter Declaration Details Page"
    When I enter "" on "Enter Declaration Details Page"
    And I click continue on "Enter Declaration Details Page"
    Then I am presented with the "Who Is The Declarant Page"
    When I select radio button "0" on "Who Is The Declarant Page"
    And I click continue on "Who Is The Declarant Page"
    Then I am presented with the "Enter Claimant Details As Individual Page"
    When I enter "" on "Enter Claimant Details As Individual Page"
    And I select radio button "true" on "Enter Claimant Details As Individual Page"
    And I click continue on "Enter Claimant Details As Individual Page"
    Then I am presented with the "Enter Claimant Details As Company Page"
    When I enter "" on "Enter Claimant Details As Company Page"
    And I click continue on "Enter Claimant Details As Company Page"
    Then I am presented with the "Enter Reason For Claim And Basis Page"
    When I select dropdown value "Duplicate MRN or Entry,Mail order goods" on "Enter Reason For Claim And Basis Page"
    And I click continue on "Enter Reason For Claim And Basis Page"
    #Then I am presented with the "Enter Duplicate Movement Reference Number Page"
    When I enter "10ABCDEFGHIJKLMNO0" on "Enter Duplicate Movement Reference Number Page"
    And I click continue on "Enter Duplicate Movement Reference Number Page"
    Then I am presented with the "Check Duplicate Declaration Details Page"
    And I click continue on "Check Duplicate Declaration Details Page"
    Then I am presented with the "Enter Commodity Details Page"
    When I enter "under 500 characters" on "Enter Commodity Details Page"
    And I click continue on "Enter Commodity Details Page"
    Then I am presented with the "Select Duties Page"
    When I select "0,1,2,3,4,5,6,7,8,9,10,11,12,13" on "Select Duties Page"
    And I click continue on "Select Duties Page"
    Then I am presented with the "Enter Claim Page" "A00 - Customs Duty"
    When I enter "2,1" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A20 - Additional Duty"
    When I enter "3,2" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A30 - Definitive Anti-Dumping Duty"
    When I enter "4,3" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A35 - Provisional Anti-Dumping Duty"
    When I enter "5,4" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A40 - Definitive Countervailing Duty"
    When I enter "6,5" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A45 - Provisional Countervailing Duty"
    When I enter "7,6" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "B00 - Value Added Tax"
    When I enter "8,7" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A50 - Customs Duty"
    When I enter "9,8" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A70 - Additional Duty"
    When I enter "10,9" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "11,10" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "12,11" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A90 - Definitive Countervailing Duty"
    When I enter "13,12" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "A95 - Provisional Countervailing Duty"
    When I enter "14,13" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Enter Claim Page" "B05 - Value Added Tax"
    When I enter "15,14" on "Enter Claim Page"
    And I click continue on "Enter Claim Page"
    Then I am presented with the "Check Claim Page"
    When I click continue on "Check Claim Page"
    Then I am presented with the "Enter Bank Account Details Page"
    When I enter "" on "Enter Bank Account Details Page"
    And I select checkbox on "Enter Bank Account Details Page"
    And I click continue on "Enter Bank Account Details Page"
    Then I am presented with the "Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Supporting Evidence Scan Progress Page"
    When I select dropdown value "Commercial Invoice" on "Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Supporting Evidence Check Your Answers Page"
    When I click continue on "Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Check Answers Accept Send Page"
    And I click continue on "Check Answers Accept Send Page"
